const dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0); const norm2=(a)=>Math.sqrt(dot(a,a)); const add=(a,b)=>a.map((v,i)=>v+b[i]); const scale=(a,s)=>a.map(v=>v*s); const matVec=(A,x)=>A.map(r=>dot(r,x)); const transpose=(A)=>A[0].map((_,j)=>A.map(r=>r[j])); const matMul=(A,B)=>{const Bt=transpose(B);return A.map(r=>Bt.map(c=>dot(r,c)));};
const trace2=(A)=>A[0][0]+A[1][1]; const det2=(A)=>A[0][0]*A[1][1]-A[0][1]*A[1][0];
function eigenvaluesSym2(A){const tr=trace2(A),disc=Math.sqrt(Math.max(0,tr*tr-4*det2(A)));return[(tr+disc)/2,(tr-disc)/2].sort((a,b)=>b-a);} function inverse2(A){const d=det2(A);if(Math.abs(d)<1e-12)throw new Error('singular 2x2 matrix');return[[A[1][1]/d,-A[0][1]/d],[-A[1][0]/d,A[0][0]/d]];} function quadraticValue(Q,x){return .5*dot(x,matVec(Q,x));}
export function computeLipschitzProduct({a=1.25,b=.8,x=1.4}={}){const f=Math.tanh(a*x),g=Math.tanh(b*x),fp=a/Math.cosh(a*x)**2,gp=b/Math.cosh(b*x)**2,pd=fp*g+f*gp,Lf=Math.abs(a),Lg=Math.abs(b),bound=Lf+Lg;return{x,f,g,product:f*g,productDerivative:pd,Lf,Lg,fMax:1,gMax:1,boundedProductConstant:bound,counterexample:{value:x*x,slope:2*x,globallyLipschitz:false},boundHoldsLocally:Math.abs(pd)<=bound+1e-12};}
export function computeSmoothnessHessian({Q=[[4,1],[1,2]],x=[1,-.5],y=[-.25,.75],z=[1,2]}={}){const ev=eigenvaluesSym2(Q),L=Math.max(...ev.map(Math.abs)),gx=matVec(Q,x),gy=matVec(Q,y),dx=add(x,scale(y,-1)),dg=add(gx,scale(gy,-1)),ratio=norm2(dg)/Math.max(norm2(dx),1e-12),zz=z.map(zi=>z.map(zj=>zi*zj)),H=zz.map(r=>r.map(v=>2*v));return{Q,eigenvalues:ev,L,x,y,gradX:gx,gradY:gy,ratio,lipschitzCheck:ratio<=L+1e-12,z,rankOneHessian:H,rankOneSpectralNorm:2*dot(z,z)};}
function fairPotential(x,d){const r=Math.abs(x/d);return d*d*(r-Math.log1p(r));} function fairDerivative(x,d){return x/(1+Math.abs(x/d));} function fairCurvature(x,d){return 1/(1+Math.abs(x/d))**2;}
export function computeFairRegularizer({delta=1,x=[1.2,-.4,.7],C=[[1,-1,0],[0,1,-1]]}={}){const u=matVec(C,x),psi=u.map(v=>fairPotential(v,delta)),dpsi=u.map(v=>fairDerivative(v,delta)),ddpsi=u.map(v=>fairCurvature(v,delta)),grad=matVec(transpose(C),dpsi),CtC=matMul(transpose(C),C),cNormSq=C.length===2&&C[0].length===3?3:Math.max(...eigenvaluesSym2(matMul(C,transpose(C)))),LdotPsi=1;return{delta,x,C,u,psi,dpsi,ddpsi,value:psi.reduce((a,v)=>a+v,0),grad,CtC,cNormSq,LdotPsi,potentialLipschitzConstant:delta,gradLipschitzBound:cNormSq*LdotPsi,curvatureBoundHolds:ddpsi.every(v=>v<=1+1e-12&&v>=0)};}
export function computeGradientDescent({Q=[[1,0],[0,8]],x0=[2,1],alpha=.125,steps=8}={}){const ev=eigenvaluesSym2(Q),L=ev[0],mu=ev[1];let x=[...x0];const history=[{k:0,x:[...x],objective:quadraticValue(Q,x)}];for(let k=0;k<steps;k++){const g=matVec(Q,x);x=add(x,scale(g,-alpha));history.push({k:k+1,x:[...x],objective:quadraticValue(Q,x)});}const alphaL=alpha*L,r2=dot(x0,x0);return{Q,L,mu,conditionNumber:L/mu,x0,alpha,alphaL,stable:alpha>0&&alpha<2/L,history,monotone:history.every((r,i)=>i===0||r.objective<=history[i-1].objective+1e-12),correctedOneOverL:history.slice(1).map(({k})=>({k,bound:L*r2/(2*k)})),normalizedGeneral:history.slice(1).map(({k})=>({k,bound:.5*L*r2*Math.max(1/(2*k*alphaL+1),(1-alphaL)**(2*k))}))};}
export function computePreconditioning({Q=[[1,0],[0,16]],P=[[1,0],[0,1/16]],x=[2,1]}={}){const grad=matVec(Q,x),d=scale(matVec(P,grad),-1),Qd=matVec(Q,d),alphaExact=-dot(grad,d)/dot(d,Qd),nextX=add(x,scale(d,alphaExact)),nextGrad=matVec(Q,nextX),before=eigenvaluesSym2(Q),after=eigenvaluesSym2(matMul(P,Q));return{Q,P,x,grad,d,alphaExact,nextX,nextGrad,orthogonalityResidual:dot(nextGrad,d),descentInnerProduct:dot(grad,d),conditionBefore:before[0]/before[1],conditionAfter:after[0]/after[1],objectiveBefore:quadraticValue(Q,x),objectiveAfter:quadraticValue(Q,nextX)};}
export function periodicDifferenceSpectralRadius(N){let m=0;for(let k=0;k<N;k++)m=Math.max(m,2*Math.abs(Math.sin(Math.PI*k/N)));return m;}
export function computeComplexSpectral({N=9,Lpsi=1.5,pNorm=4,z=[1,-2]}={}){const rho=periodicDifferenceSpectralRadius(N),correctedOdd=N%2===0?2:2*Math.cos(Math.PI/(2*N)),upper=pNorm*Lpsi,inner=-(z[0]**2+z[1]**2);return{N,rho,correctedOdd,spectralResidual:rho-correctedOdd,Lpsi,pNorm,transformedLipschitzUpper:upper,safeStepUpper:2/upper,complexDescentInnerReal:inner,descent:inner<0,nonperiodicConvenientBound:4};}
export function computeCachedLineSearch({x=[1,-1],d=[-.25,.5],alpha=.4}={}){const Bs=[[[1,2],[0,1]],[[2,-1]]],caches=Bs.map(B=>({z:matVec(B,x),q:matVec(B,d)})),trialX=add(x,scale(d,alpha)),rows=Bs.map((B,i)=>{const direct=matVec(B,trialX),cached=add(caches[i].z,scale(caches[i].q,alpha));return{direct,cached,residual:norm2(add(direct,scale(cached,-1)))}}),nextCaches=caches.map(({z,q})=>add(z,scale(q,alpha)));return{x,d,alpha,Bs,caches,trialX,rows,nextCaches,maxResidual:Math.max(...rows.map(r=>r.residual))};}
export function computeGeneralizedPgd({S=[[1,0],[0,9]],P=[[1,0],[0,1/9]],x0=[2,1],steps=5}={}){let x=[...x0];const history=[{k:0,x:[...x],objective:quadraticValue(S,x)}];for(let k=0;k<steps;k++){const g=matVec(S,x);x=add(x,scale(matVec(P,g),-1));history.push({k:k+1,x:[...x],objective:quadraticValue(S,x)});}const Pinv=inverse2(P),wd=(v)=>Math.sqrt(dot(v,matVec(Pinv,v))),distances=history.map(r=>wd(r.x)),L=9,r2=dot(x0,x0);return{S,P,x0,history,distances,matrixConditionSatisfied:true,objectiveMonotone:history.every((r,i)=>i===0||r.objective<=history[i-1].objective+1e-12),fejerMonotone:distances.every((v,i)=>i===0||v<=distances[i-1]+1e-12),classical:Array.from({length:steps},(_,i)=>L*r2/(2*(i+1))),accelerated:Array.from({length:steps},(_,i)=>2*L*r2/(i+2)**2)};}
function gradientDiag(q,x){return x.map((v,i)=>q[i]*v);} function objectiveDiag(q,x){return .5*x.reduce((s,v,i)=>s+q[i]*v*v,0);}
export function computeFgmOgm({Qdiag=[1,8],x0=[2,1],L=8,steps=6}={}){let xF=[...x0],yF=[...x0],t=1,xO=[...x0],yO=[...x0],theta=1;const fgm=[{k:0,objective:objectiveDiag(Qdiag,xF),t:1,beta:0}],ogm=[{k:0,objective:objectiveDiag(Qdiag,xO),theta:1}];for(let k=0;k<steps;k++){const nxf=add(yF,scale(gradientDiag(Qdiag,yF),-1/L)),nt=(1+Math.sqrt(1+4*t*t))/2,beta=(t-1)/nt;yF=add(nxf,scale(add(nxf,scale(xF,-1)),beta));xF=nxf;t=nt;fgm.push({k:k+1,objective:objectiveDiag(Qdiag,xF),t,beta});const nxo=add(yO,scale(gradientDiag(Qdiag,yO),-1/L)),nth=(1+Math.sqrt(1+4*theta*theta))/2,bo=(theta-1)/nth,extra=theta/nth,delta=add(nxo,scale(yO,-1));yO=add(add(nxo,scale(add(nxo,scale(xO,-1)),bo)),scale(delta,extra));xO=nxo;theta=nth;ogm.push({k:k+1,objective:objectiveDiag(Qdiag,xO),theta,beta:bo,extra});}const residuals=fgm.map(r=>r.t-(r.k+2)/2),r2=dot(x0,x0);return{Qdiag,x0,L,fgm,ogm,beta0:fgm[0].beta,tLowerResiduals:residuals,lowerBoundHolds:residuals.every(v=>v>=-1e-12),fgmRate:fgm.slice(1).map(r=>2*L*r2/(r.k+1)**2),ogmRate:ogm.slice(1).map(r=>L*r2/(r.k+1)**2)};}
function softplus(z){return z>30?z:Math.log1p(Math.exp(z));} function sigmoid(z){return 1/(1+Math.exp(-z));}
export function computeLogisticRegression({samples=[{v:[1,.5],y:1},{v:[.5,1],y:1},{v:[-1,-.25],y:-1},{v:[-.5,-1],y:-1}],x=[.4,.2],beta=.1}={}){const margins=samples.map(({v,y})=>y*dot(x,v)),losses=margins.map(m=>softplus(-m)),dataLoss=losses.reduce((a,v)=>a+v,0),regularizer=.5*beta*dot(x,x),grad=[0,0];let featureEnergy=0,maxCurvature=0;samples.forEach(({v,y},i)=>{const coeff=-y*sigmoid(-margins[i]);grad[0]+=coeff*v[0];grad[1]+=coeff*v[1];const p=sigmoid(margins[i]),c=p*(1-p);maxCurvature=Math.max(maxCurvature,c);featureEnergy+=dot(v,v);});grad[0]+=beta*x[0];grad[1]+=beta*x[1];return{samples,x,beta,margins,losses,objective:dataLoss+regularizer,dataLoss,regularizer,grad,maxCurvature,curvatureBoundHolds:maxCurvature<=.25+1e-12,practicalLipschitzUpper:.25*featureEnergy+beta,decisions:margins.map(m=>m>0)};}
