<script>
 import { computeConvolutionPrimitives } from '@/lib/formula-lessons/part3-advanced.mjs';
 export let lesson; export let spec;
 let t=spec.t;
 $: r=computeConvolutionPrimitives({...spec,t:Number(t)});
 const f=(v,d=4)=>Number(v).toFixed(d);
</script>
<div class="grid" data-convolution-primitives-lesson data-focus={lesson.focus}><section class="panel"><p class="eyebrow">continuous convolution instance</p><h6>(f∗g)({f(t,2)}) = {f(r.continuous)}</h6><label>t <output>{f(t,2)}</output><input bind:value={t} type="range" min="-2" max="2" step="0.05"/></label><p class="small">f,g는 이 integral을 수치적으로 읽기 위한 Gaussian instance다. source 정의 자체는 일반 함수에 대한 식이다.</p></section><section class="panel"><p class="eyebrow">two discrete forms</p><div class="seq"><span>Σ f[m]g[n−m]</span><strong>[{r.first.join(', ')}]</strong></div><div class="seq"><span>Σ f[n−m]g[m]</span><strong>[{r.second.join(', ')}]</strong></div><div class="status">same sequence: {r.equivalent1d?'PASS':'FAIL'}</div></section></div><section class="panel matrix-panel"><p class="eyebrow">2D LSI convolution · output support {r.support2d[0]}×{r.support2d[1]}</p><div class="matrix">{#each r.twoD as row,i (i)}<div>{#each row as value,j (j)}<span>{f(value,2)}</span>{/each}</div>{/each}</div></section>
<style>.grid{display:grid;grid-template-columns:1fr 1fr;gap:.8rem}.panel{border:1px solid var(--color-border);border-radius:1rem;background:var(--color-background);padding:1rem}.eyebrow{margin:0 0 .55rem;font-size:.66rem;font-weight:900;text-transform:uppercase;letter-spacing:.1em;color:var(--color-muted-foreground)}h6{margin:.2rem 0 .7rem}.panel label{display:grid;grid-template-columns:1fr auto;gap:.2rem;font-size:.72rem;font-weight:800}.panel input{grid-column:1/-1;min-height:30px}.small,.status{font-size:.72rem;color:var(--color-muted-foreground)}.seq{display:flex;justify-content:space-between;gap:.5rem;background:var(--color-muted);padding:.65rem;border-radius:.65rem;margin:.45rem 0;font-size:.72rem}.matrix-panel{margin-top:.8rem}.matrix{display:grid;gap:.2rem;overflow-x:auto}.matrix>div{display:flex;gap:.2rem}.matrix span{min-width:3.2rem;text-align:right;background:var(--color-muted);border-radius:.35rem;padding:.35rem;font-size:.7rem}@media(max-width:760px){.grid{grid-template-columns:1fr}}</style>
