<script>
 import { computeBoundaryLesson, positiveMod } from '@/lib/formula-lessons/part3-advanced.mjs';
 export let lesson; export let spec;
 let mode='zero';
 $: r=computeBoundaryLesson({x:spec.x,h:spec.h});
 $: matrix=mode==='zero'?r.zeroMatrix:mode==='periodic'?r.periodicMatrix:r.extendedMatrix;
 $: output=mode==='zero'?r.zeroOutput:mode==='periodic'?r.periodicOutput:mode==='mirror'?r.mirrorOutput:r.extendedOutput;
 const f=(v,d=2)=>Number(v).toFixed(d);
</script>
<div class="grid" data-convolution-boundary-lesson data-focus={lesson.focus}><section class="panel"><p class="eyebrow">boundary condition → system matrix</p><select bind:value={mode} aria-label="boundary condition"><option value="zero">zero</option><option value="extended">extended (zero outside)</option><option value="periodic">periodic</option><option value="mirror">mirror</option></select><div class="matrix">{#each matrix as row,i (i)}<div>{#each row as v,j (j)}<span>{v}</span>{/each}</div>{/each}</div></section><section class="panel"><p class="eyebrow">y=Ax / circular checks</p><div class="metric"><span>x</span><strong>[{spec.x.join(', ')}]</strong></div><div class="metric"><span>output</span><strong>[{output.join(', ')}]</strong></div><div class="metric"><span>h̃</span><strong>[{r.ht.join(', ')}]</strong></div><div class="metric"><span>periodic residual</span><strong>{f(r.periodicResidual,8)}</strong></div><div class="metric"><span>(−1) mod 6</span><strong>{positiveMod(-1,6)}</strong></div><div class="metric"><span>7 mod 6</span><strong>{positiveMod(7,6)}</strong></div></section></div>
<aside class="note">같은 3-tap h[n]={2,4,1}과 N=6에서 Figure 4의 zero·extended·periodic matrix entry를 그대로 재현한다. periodic matrix multiplication은 MAI-P3-116의 circular sum과 일치하며, mirror는 MAI-P3-122의 반사 경계를 사용한다.</aside>
<style>.grid{display:grid;grid-template-columns:1.25fr .75fr;gap:.8rem}.panel,.note{border:1px solid var(--color-border);border-radius:1rem;background:var(--color-background);padding:1rem}.eyebrow{margin:0 0 .55rem;font-size:.66rem;font-weight:900;text-transform:uppercase;letter-spacing:.1em;color:var(--color-muted-foreground)}select{width:100%;min-height:2.2rem;border:1px solid var(--color-border);border-radius:.6rem;background:var(--color-background);padding:.35rem}.matrix{display:grid;gap:.15rem;margin-top:.7rem;overflow-x:auto}.matrix>div{display:flex;gap:.15rem}.matrix span{min-width:2rem;text-align:center;background:var(--color-muted);padding:.3rem;border-radius:.3rem;font-size:.68rem}.metric{display:flex;justify-content:space-between;gap:.5rem;background:var(--color-muted);border-radius:.65rem;padding:.6rem;margin:.4rem 0;font-size:.72rem}.note{margin-top:.8rem;font-size:.74rem;line-height:1.65}@media(max-width:760px){.grid{grid-template-columns:1fr}}</style>
