<script>
 import { computeConvolutionExercises } from '@/lib/formula-lessons/part3-advanced.mjs';
 export let lesson; export let spec;
 let M=spec.reductionKernelSize;
 $: r=computeConvolutionExercises({image:spec.image,kernel:spec.kernel,reductionKernelSize:Number(M)});
 const f=(v,d=3)=>Number(v).toFixed(d);
</script>
<div class="grid" data-convolution-exercises-lesson data-focus={lesson.focus}><section class="panel"><p class="eyebrow">source kernel → 180° mirror</p><div class="pair"><div><strong>h[k,l]</strong><div class="matrix">{#each spec.kernel as row,i (i)}<div>{#each row as v,j (j)}<span>{v}</span>{/each}</div>{/each}</div></div><div><strong>h[-k,-l]</strong><div class="matrix">{#each r.mirrored as row,i (i)}<div>{#each row as v,j (j)}<span>{v}</span>{/each}</div>{/each}</div></div></div><p class="small">MAI-P3-081의 ?는 MAI-P3-154가 별도 완성한다.</p></section><section class="panel"><p class="eyebrow">checkerboard + separable saving</p><div class="metric"><span>3×3 average response</span><strong>{f(r.checkerResponse,6)}</strong></div><div class="metric"><span>separable residual</span><strong>{f(r.separableResidual,10)}</strong></div><label>square kernel M <output>{M}</output><input bind:value={M} type="range" min="3" max="9" step="1"/></label><div class="saving">reduction = {f(r.reduction,2)}%</div></section></div><section class="panel output"><p class="eyebrow">completed full convolution · support {r.support[0]}×{r.support[1]}</p><div class="matrix wide">{#each r.output as row,i (i)}<div>{#each row as v,j (j)}<span>{v}</span>{/each}</div>{/each}</div></section>
<aside class="note">MAI-P3-083/087/096의 미완성 값은 원문 그대로 유지되고, 각각 MAI-P3-155/156/157이 계산된 완성형이다. 2D direct와 두 번의 1D separable convolution 결과는 동일하게 검산된다.</aside>
<style>.grid{display:grid;grid-template-columns:1fr 1fr;gap:.8rem}.panel,.note{border:1px solid var(--color-border);border-radius:1rem;background:var(--color-background);padding:1rem}.eyebrow{margin:0 0 .6rem;font-size:.66rem;font-weight:900;text-transform:uppercase;letter-spacing:.1em;color:var(--color-muted-foreground)}.pair{display:grid;grid-template-columns:1fr 1fr;gap:.8rem}.matrix{display:grid;gap:.2rem;margin-top:.4rem;overflow-x:auto}.matrix>div{display:flex;gap:.2rem}.matrix span{min-width:2.4rem;text-align:center;background:var(--color-muted);padding:.35rem;border-radius:.35rem;font-size:.7rem}.wide span{min-width:2.2rem}.metric{display:flex;justify-content:space-between;gap:.4rem;background:var(--color-muted);border-radius:.65rem;padding:.6rem;margin:.4rem 0;font-size:.72rem}.panel label{display:grid;grid-template-columns:1fr auto;gap:.2rem;margin-top:.6rem;font-size:.72rem;font-weight:800}.panel input{grid-column:1/-1;min-height:30px}.saving,.small{font-size:.72rem;margin-top:.55rem}.output,.note{margin-top:.8rem}.note{font-size:.74rem;line-height:1.65}@media(max-width:760px){.grid{grid-template-columns:1fr}.pair{grid-template-columns:1fr 1fr}}</style>
