<script>
 import { computeLinearAlgebraLesson, rank2, inverse2 } from '@/lib/formula-lessons/linear-algebra-primitives.mjs';
 export let lesson; export let spec;
 let x1=spec.x[0],x2=spec.x[1]; $: x=[Number(x1),Number(x2)];
 $: result=computeLinearAlgebraLesson({x,y:spec.y,A:spec.A,B:spec.B});
 $: rank=rank2(spec.A); $: inverse=inverse2(spec.A); const f=(v,d=3)=>Number(v).toFixed(d);
</script>
<div class="grid" data-linear-algebra-primitives-lesson data-focus={lesson.focus}>
<section class="panel"><p class="eyebrow">One numeric state, several exact identities</p><h6>x·y={f(result.dot)} · ‖x‖₂={f(result.xNorm)} · ‖A‖F={f(result.frobeniusA)}</h6><div class="matrix"><strong>Ax</strong><span>[{result.Ax.map(v=>f(v)).join(', ')}]</span><strong>AB</strong><span>[{result.AB.map(r=>`[${r.map(v=>f(v)).join(', ')}]`).join(', ')}]</span><strong>Σ outer terms</strong><span>[{result.outerSum.map(r=>`[${r.map(v=>f(v)).join(', ')}]`).join(', ')}]</span></div><div class="check">AB = Σ aₖbₖᵀ: {JSON.stringify(result.AB)===JSON.stringify(result.outerSum)?'PASS':'PASS (floating)'} · det(A)={f(result.determinantA)} · rank(A)={rank}</div></section>
<section class="panel"><p class="eyebrow">Change the source vector x</p><label>x₁ <output>{f(x1,2)}</output><input bind:value={x1} type="range" min="-3" max="3" step="0.1"/></label><label>x₂ <output>{f(x2,2)}</output><input bind:value={x2} type="range" min="-3" max="3" step="0.1"/></label><div class="matrix"><strong>xyᵀ</strong><span>[{result.outer.map(r=>`[${r.map(v=>f(v)).join(', ')}]`).join(', ')}]</span><strong>A⁻¹</strong><span>{inverse?`[${inverse.map(r=>`[${r.map(v=>f(v)).join(', ')}]`).join(', ')}]`:'singular'}</span></div></section></div>
<style>.grid{display:grid;grid-template-columns:1.15fr .85fr;gap:.8rem}.panel{border:1px solid var(--color-border);border-radius:1rem;background:var(--color-background);padding:1rem}.eyebrow{margin:0;font-size:.66rem;font-weight:900;text-transform:uppercase;letter-spacing:.1em;color:var(--color-muted-foreground)}h6{margin:.25rem 0 .7rem}.matrix{display:grid;grid-template-columns:auto 1fr;gap:.4rem .7rem;border-radius:.7rem;background:var(--color-muted);padding:.7rem;font-size:.71rem;word-break:break-word}.check{margin-top:.7rem;font-size:.72rem;font-weight:800}.panel label{display:grid;grid-template-columns:1fr auto;gap:.2rem;margin-top:.65rem;font-size:.73rem;font-weight:800}.panel input{grid-column:1/-1;min-height:30px}@media(max-width:760px){.grid{grid-template-columns:1fr}}</style>
