<script>
  import { computeLipschitzProduct, computeSmoothnessHessian } from '@/lib/formula-lessons/part4-models.mjs';
  export let lesson; export let spec;
  let x=spec.x??1.4,a=spec.a??1.25,b=spec.b??.8;
  $: product=spec.scene==='lipschitz-product'?computeLipschitzProduct({a:Number(a),b:Number(b),x:Number(x)}):null;
  $: smooth=spec.scene==='smoothness-hessian'?computeSmoothnessHessian(spec):null;
  const f=(v,d=4)=>Number(v).toFixed(d);
</script>
<div class="lesson-grid" data-part4-lipschitz-lesson data-focus={lesson.focus} data-scene={spec.scene}>
{#if product}<section class="panel"><p class="eyebrow">bounded product · exact-ID</p><div class="metrics"><div><span>f(x)</span><strong>{f(product.f)}</strong></div><div><span>g(x)</span><strong>{f(product.g)}</strong></div><div><span>|(fg)'|</span><strong>{f(Math.abs(product.productDerivative))}</strong></div><div><span>safe bound</span><strong>{f(product.boundedProductConstant)}</strong></div></div><label>x <output>{f(x,2)}</output><input bind:value={x} type="range" min="-3" max="3" step=".05"/></label><label>a <output>{f(a,2)}</output><input bind:value={a} type="range" min=".25" max="2" step=".05"/></label><label>b <output>{f(b,2)}</output><input bind:value={b} type="range" min=".25" max="2" step=".05"/></label></section><section class="panel"><p class="eyebrow">why the global product claim fails</p><svg viewBox="0 0 340 220" role="img" aria-label="bounded product and x squared comparison"><line class="axis" x1="25" y1="180" x2="320" y2="180"/><line class="axis" x1="170" y1="20" x2="170" y2="200"/><path class="curve" d="M30 159 C95 130 135 82 170 70 C205 82 245 130 310 159"/><path class="counter" d="M45 35 Q170 195 295 35"/></svg><p class="note">x² slope={f(product.counterexample.slope,2)} and grows without bound. Bounded-factor derivative check: <strong>{product.boundHoldsLocally?'PASS':'FAIL'}</strong>.</p></section>
{:else if smooth}<section class="panel"><p class="eyebrow">smooth quadratic · exact-ID</p><div class="metrics"><div><span>λmax(Q)</span><strong>{f(smooth.L)}</strong></div><div><span>||Δ∇f||/||Δx||</span><strong>{f(smooth.ratio)}</strong></div><div><span>≤L?</span><strong>{smooth.lipschitzCheck?'PASS':'FAIL'}</strong></div><div><span>rank-one ||H||₂</span><strong>{f(smooth.rankOneSpectralNorm,0)}</strong></div></div><p class="note">Quadratic smoothness constant and Hessian spectral norm share the same numeric core.</p></section><section class="panel"><p class="eyebrow">PDF rank-one example</p><div class="matrix">{#each smooth.rankOneHessian as row,i (i)}<div>{row.map(v=>f(v,0)).join('   ')}</div>{/each}</div><p class="note">z=[1,2] gives 2||z||²=10, reproducing MAI-P4-036.</p></section>{/if}
</div>
<style>.lesson-grid{display:grid;grid-template-columns:1fr 1fr;gap:.8rem}.panel{border:1px solid var(--color-border);border-radius:1rem;background:var(--color-background);padding:1rem}.eyebrow{margin:0 0 .5rem;font-size:.66rem;font-weight:900;text-transform:uppercase;letter-spacing:.1em;color:var(--color-muted-foreground)}.metrics{display:grid;grid-template-columns:1fr 1fr;gap:.4rem}.metrics div{display:grid;background:var(--color-muted);border-radius:.65rem;padding:.55rem;font-size:.72rem}.metrics span{color:var(--color-muted-foreground)}label{display:grid;grid-template-columns:1fr auto;margin-top:.45rem;font-size:.72rem;font-weight:800}input{grid-column:1/-1;min-height:30px}svg{width:100%;max-height:14rem}.axis{stroke:var(--color-border)}.curve{fill:none;stroke:var(--color-primary);stroke-width:3}.counter{fill:none;stroke:var(--color-foreground);stroke-width:2;stroke-dasharray:7 5}.note{font-size:.73rem;line-height:1.65;color:var(--color-muted-foreground)}.matrix{font-family:ui-monospace,monospace;white-space:pre;text-align:center;background:var(--color-muted);border-radius:.8rem;padding:1rem;line-height:2}@media(max-width:760px){.lesson-grid{grid-template-columns:1fr}}</style>
