<script>
 import { computeMlpForward } from '@/lib/formula-lessons/part3-advanced.mjs';
 export let lesson; export let spec;
 let x1=spec.x[0],x2=spec.x[1];
 $: r=computeMlpForward({x:[Number(x1),Number(x2)],W2:spec.W2,b2:spec.b2,W3:spec.W3,b3:spec.b3,batchX:spec.batchX});
 const f=(v,d=3)=>Number(v).toFixed(d);
</script>
<div class="grid" data-mlp-forward-lesson data-focus={lesson.focus}><section class="panel"><p class="eyebrow">2 → 3 → 2 forward</p><div class="layer"><span>input a(1)</span><strong>[{f(x1)}, {f(x2)}]</strong></div><div class="layer"><span>z(2)</span><strong>[{r.z2.map(v=>f(v)).join(', ')}]</strong></div><div class="layer"><span>ReLU a(2)</span><strong>[{r.a2.map(v=>f(v)).join(', ')}]</strong></div><div class="layer"><span>z(L)</span><strong>[{r.z3.map(v=>f(v)).join(', ')}]</strong></div>{#each r.probabilities as p,i (i)}<div class="prob"><span>class {i+1}</span><i style={`width:${p*100}%`}></i><strong>{f(p)}</strong></div>{/each}<div class="winner">argmax → class {r.predictedClass+1} · Σsoftmax={f(r.probabilitySum,8)}</div><label>x₁ <output>{f(x1,2)}</output><input bind:value={x1} type="range" min="-1" max="1" step="0.05"/></label><label>x₂ <output>{f(x2,2)}</output><input bind:value={x2} type="range" min="-1" max="1" step="0.05"/></label></section><section class="panel"><p class="eyebrow">matrix / batch shape contract</p>{#each Object.entries(r.shapes) as entry (entry[0])}<div class="shape"><span>{entry[0]}</span><strong>{entry[1][0]}×{entry[1][1]}</strong></div>{/each}<div class="batch"><strong>batch softmax sums</strong><span>[{r.batchProbabilitySums.map(v=>f(v,8)).join(', ')}]</span></div></section></div>
<aside class="note">MAI-P3-053/057/068의 <code>N_L</code> 혼용과 MAI-P3-060의 <code>??</code> weight matrix는 원문 상태로 남는다. 이 장면의 shape 계산은 각각 MAI-P3-151/152/153과 MAI-P3-150 교정·완성형을 사용한다.</aside>
<style>.grid{display:grid;grid-template-columns:1fr .8fr;gap:.8rem}.panel,.note{border:1px solid var(--color-border);border-radius:1rem;background:var(--color-background);padding:1rem}.eyebrow{margin:0 0 .55rem;font-size:.66rem;font-weight:900;text-transform:uppercase;letter-spacing:.1em;color:var(--color-muted-foreground)}.layer,.shape,.batch{display:flex;justify-content:space-between;gap:.6rem;background:var(--color-muted);border-radius:.65rem;padding:.55rem;margin:.4rem 0;font-size:.72rem}.layer span,.shape span{color:var(--color-muted-foreground)}.prob{display:grid;grid-template-columns:4rem 1fr 4rem;gap:.4rem;align-items:center;font-size:.72rem;margin:.45rem 0}.prob i{height:.75rem;border-radius:99px;background:var(--color-primary)}.winner{font-size:.72rem;margin:.6rem 0}.panel label{display:grid;grid-template-columns:1fr auto;gap:.2rem;margin-top:.55rem;font-size:.72rem;font-weight:800}.panel input{grid-column:1/-1;min-height:30px}.note{margin-top:.8rem;font-size:.74rem;line-height:1.65}@media(max-width:760px){.grid{grid-template-columns:1fr}}</style>
