<script>
 import { computePatchCnn } from '@/lib/formula-lessons/part3-advanced.mjs';
 export let lesson; export let spec;
 let h1=spec.h[0];
 $: h=[Number(h1),spec.h[1],spec.h[2]];
 $: r=computePatchCnn({...spec,h});
 const f=(v,d=2)=>Number(v).toFixed(d);
</script>
<div class="grid" data-patch-cnn-lesson data-focus={lesson.focus}><section class="panel"><p class="eyebrow">W(s) → zₛ → Z → g=Zh</p><label>h₁ <output>{f(h1)}</output><input bind:value={h1} type="range" min="-2" max="2" step="0.1"/></label><div class="matrix">{#each r.Z as row,i (i)}<div>{#each row as v,j (j)}<span>{f(v)}</span>{/each}</div>{/each}</div><div class="metric"><span>h</span><strong>[{h.map(v=>f(v)).join(', ')}]</strong></div><div class="metric"><span>g</span><strong>[{r.g.map(v=>f(v)).join(', ')}]</strong></div></section><section class="panel"><p class="eyebrow">Conv2d source setup</p><div class="metric"><span>channels</span><strong>{spec.conv.inChannels} → {spec.conv.outChannels}</strong></div><div class="metric"><span>K / p / s</span><strong>{spec.conv.kernelSize} / {spec.conv.padding} / {spec.conv.stride}</strong></div><div class="metric"><span>spatial 8 →</span><strong>{r.convOutputSpatial}</strong></div><div class="metric"><span>parameters+bias</span><strong>{r.convParameters.toLocaleString()}</strong></div></section></div><section class="panel pool"><p class="eyebrow">MaxPool K=3,s=2,p=1 · completed output</p><div class="matrix">{#each r.pooled.output as row,i (i)}<div>{#each row as v,j (j)}<span>{v}</span>{/each}</div>{/each}</div></section>
<aside class="note">MAI-P3-128의 <code>y</code>-patch와 MAI-P3-134의 고립된 <code>x</code>는 source-suspect로 보존하고, 수치 patch/design-matrix 계산은 MAI-P3-158/159 교정형을 따른다. MaxPool 3×3 결과는 MAI-P3-140의 빈 칸을 MAI-P3-160으로 완성한 값이다.</aside>
<style>.grid{display:grid;grid-template-columns:1fr 1fr;gap:.8rem}.panel,.note{border:1px solid var(--color-border);border-radius:1rem;background:var(--color-background);padding:1rem}.eyebrow{margin:0 0 .55rem;font-size:.66rem;font-weight:900;text-transform:uppercase;letter-spacing:.1em;color:var(--color-muted-foreground)}label{display:grid;grid-template-columns:1fr auto;gap:.2rem;font-size:.72rem;font-weight:800}input{grid-column:1/-1;min-height:30px}.matrix{display:grid;gap:.2rem;margin:.7rem 0;overflow-x:auto}.matrix>div{display:flex;gap:.2rem}.matrix span{min-width:2.8rem;text-align:center;background:var(--color-muted);padding:.35rem;border-radius:.35rem;font-size:.7rem}.metric{display:flex;justify-content:space-between;gap:.5rem;background:var(--color-muted);border-radius:.65rem;padding:.6rem;margin:.4rem 0;font-size:.72rem}.pool,.note{margin-top:.8rem}.note{font-size:.74rem;line-height:1.65}@media(max-width:760px){.grid{grid-template-columns:1fr}}</style>
