<script>
  import { computePerceptronMse } from '@/lib/formula-lessons/part3-advanced.mjs';
  export let lesson; export let spec;
  let w1=spec.initialW[0], w2=spec.initialW[1], alpha=spec.alpha;
  $: result=computePerceptronMse({samples:spec.samples,w:[Number(w1),Number(w2)],alpha:Number(alpha)});
  const f=(v,d=4)=>Number(v).toFixed(d);
</script>
<div class="grid" data-perceptron-mse-lesson data-focus={lesson.focus}>
  <section class="panel"><p class="eyebrow">½Σ residual²</p><h6>L={f(result.loss)} → next {f(result.nextLoss)}</h6><table><thead><tr><th>sample</th><th>ŷ</th><th>r=y−ŷ</th><th>r²</th></tr></thead><tbody>{#each result.rows as row (row.id)}<tr><td>{row.id}</td><td>{f(row.prediction)}</td><td>{f(row.residual)}</td><td>{f(row.squared)}</td></tr>{/each}</tbody></table></section>
  <section class="panel"><p class="eyebrow">gradient · Hessian · α bound</p><div class="metric"><span>∇L</span><strong>[{result.gradient.map(v=>f(v)).join(', ')}]</strong></div><div class="metric"><span>H</span><strong>{result.hessian.map(row=>`[${row.map(v=>f(v,2)).join(', ')}]`).join(' ')}</strong></div><div class="metric"><span>λmax</span><strong>{f(result.lambdaMax)}</strong></div><div class="metric"><span>0&lt;α&lt;2/λmax</span><strong>{f(result.alphaUpper)}</strong></div><div class="metric"><span>current α</span><strong>{result.alphaStable?'stable range':'outside bound'}</strong></div>
  <label>w₁ <output>{f(w1,2)}</output><input bind:value={w1} type="range" min="-1" max="1" step="0.05"/></label><label>w₂/b <output>{f(w2,2)}</output><input bind:value={w2} type="range" min="-1" max="1" step="0.05"/></label><label>α <output>{f(alpha,2)}</output><input bind:value={alpha} type="range" min="0.02" max="0.5" step="0.01"/></label></section>
</div>
<aside class="note"><strong>Source/correction gate.</strong> MAI-P3-043의 gradient는 원문 <code>??</code> 그대로이고 MAI-P3-146이 완성식이다. 원문 MAI-P3-045의 고정 상한 대신 MAI-P3-147의 Hessian λmax 의존 상한을 계산한다. MSE는 MAI-P3-161처럼 0을 포함하는 비음수다.</aside>
<style>.grid{display:grid;grid-template-columns:1fr 1fr;gap:.8rem}.panel,.note{border:1px solid var(--color-border);border-radius:1rem;background:var(--color-background);padding:1rem}.eyebrow{margin:0;font-size:.66rem;font-weight:900;text-transform:uppercase;letter-spacing:.1em;color:var(--color-muted-foreground)}h6{margin:.3rem 0 .7rem}table{width:100%;border-collapse:collapse;font-size:.72rem}th,td{padding:.42rem;border-bottom:1px solid var(--color-border);text-align:right}th:first-child,td:first-child{text-align:left}.metric{display:flex;justify-content:space-between;gap:.7rem;border-radius:.65rem;background:var(--color-muted);padding:.55rem;margin:.35rem 0;font-size:.72rem}.metric span{color:var(--color-muted-foreground)}label{display:grid;grid-template-columns:1fr auto;gap:.2rem;margin-top:.5rem;font-size:.72rem;font-weight:800}input{grid-column:1/-1;min-height:30px}.note{margin-top:.8rem;font-size:.74rem;line-height:1.65}@media(max-width:760px){.grid{grid-template-columns:1fr}}</style>
