<script>
  import { computeXorGeometry } from '@/lib/formula-lessons/part3-advanced.mjs';
  export let lesson; export let spec;
  let lower=spec.lower, upper=spec.upper;
  $: result=computeXorGeometry({lower:Number(lower),upper:Number(upper)});
  const px=(x)=>55+190*x, py=(y)=>245-190*y; const f=(v,d=2)=>Number(v).toFixed(d);
</script>
<div class="grid" data-xor-geometry-lesson data-focus={lesson.focus}>
<section class="panel"><p class="eyebrow">XOR geometry</p><svg viewBox="0 0 300 300" role="img" aria-label="XOR 네 점과 두 평행 결정 경계"><line class="axis" x1="35" y1="245" x2="270" y2="245"/><line class="axis" x1="55" y1="265" x2="55" y2="30"/><line class="boundary" x1={px(0)} y1={py(lower)} x2={px(lower)} y2={py(0)}/><line class="boundary" x1={px(Math.max(0,upper-1))} y1={py(1)} x2={px(1)} y2={py(Math.max(0,upper-1))}/>{#each result.points as point (point.id)}<circle class:s1={point.label==='S1'} class:s2={point.label==='S2'} cx={px(point.x[0])} cy={py(point.x[1])} r="9"/><text x={px(point.x[0])+12} y={py(point.x[1])-10}>{point.id}</text>{/each}</svg></section>
<section class="panel"><p class="eyebrow">s=x₁+x₂ rule</p><div class="count"><span>hidden minimum</span><strong>{result.hiddenUnits}</strong><span>non-input minimum</span><strong>{result.nonInputUnits}</strong></div>{#each result.points as point (point.id)}<div class="row"><span>{point.id}</span><span>s={f(point.s)}</span><strong>{point.predicted}</strong><span>{point.correct?'✓':'✗'}</span></div>{/each}<label>lower <output>{f(lower)}</output><input bind:value={lower} type="range" min="0.1" max="0.9" step="0.05"/></label><label>upper <output>{f(upper)}</output><input bind:value={upper} type="range" min="1.1" max="1.9" step="0.05"/></label><div class="status">all four classified: {result.allCorrect?'PASS':'NO'}</div></section></div>
<aside class="note">MAI-P3-049/050은 원문의 빈 답을 보존한다. 실제 두 평행선 규칙은 MAI-P3-148, 최소 hidden/non-input unit 수는 MAI-P3-149의 editorial completion으로 별도 등록되어 있다.</aside>
<style>.grid{display:grid;grid-template-columns:1fr 1fr;gap:.8rem}.panel,.note{border:1px solid var(--color-border);border-radius:1rem;background:var(--color-background);padding:1rem}.eyebrow{margin:0 0 .5rem;font-size:.66rem;font-weight:900;text-transform:uppercase;letter-spacing:.1em;color:var(--color-muted-foreground)}svg{width:100%;max-height:19rem}.axis{stroke:var(--color-border)}.boundary{stroke:var(--color-primary);stroke-width:2;stroke-dasharray:6 5}.s1{fill:var(--color-foreground)}.s2{fill:var(--color-primary)}text{fill:var(--color-muted-foreground);font-size:12px}.count{display:grid;grid-template-columns:1fr auto;gap:.35rem;background:var(--color-muted);padding:.7rem;border-radius:.7rem;font-size:.72rem}.row{display:grid;grid-template-columns:2.5rem 1fr 2.5rem 1rem;gap:.4rem;padding:.45rem 0;border-bottom:1px solid var(--color-border);font-size:.72rem}label{display:grid;grid-template-columns:1fr auto;gap:.2rem;margin-top:.55rem;font-size:.72rem;font-weight:800}input{grid-column:1/-1;min-height:30px}.status,.note{margin-top:.7rem;font-size:.74rem}.note{line-height:1.65}@media(max-width:760px){.grid{grid-template-columns:1fr}}</style>
